---
title: "unit4_ncellini_hw4"
author: "Nicholas R. Cellini"
date: "June 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1

#### Question 1a
```{r echo=TRUE}
# not running for this homework: 
# install.packages("fivethirtyeight")
```

#### Question 1b
```{r}
df <- fivethirtyeight::college_all_ages
```

#### Question 1c
```{r}
# vignette("fivethirtyeight", package = "fivethirtyeight")
# http://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/
```


#### Question 1d
```{r}
str(df)
```

### Question 2

#### Question 2a
```{r}
colnames(df)
ncol(df)
```

#### Question 2b
```{r}
library(plyr)
major_count <- table(df$major_category)
matrix_major_count <- as.matrix(major_count)
```

#### Question 2c
```{r}
par(las=2)
barplot(major_count,main="Frequency of Major Categories",col="green",horiz=TRUE,xlab="Frequency",ylab="Category of majors")
```

#### Question 2d
```{r}
write.csv(major_count, file = "major_count_csv",row.names = FALSE)
```

### Question 3
#####Github Repository:
######https://github.com/nickcellini/DDS-6306-Homework-Repo/tree/Homework

